on:
    push:
        tags:
            - "v*"

name: Create + Build release from tag and push to Docker Hub

jobs:
    buildContainer:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - uses: docker/build-push-action@v1.0.1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: oase/jennybot
            tags: latest
            tag_with_ref: true
            add_git_labels: true
            push: ${{ startsWith(github.ref, 'refs/tags/') }}